feat: url link para google maps #75
practice-uffs/app-boas-vindas pull request #79
Opened 2022-06-15 02:06 UTC by CleissonVieira

Fix: #75 

Adicionei no campo extra o link da localização de chapecó do google maps ([linha 12](https://docs.google.com/spreadsheets/d/1lcsNj0vZzBjDdN31SBzMuz1VC6yuaxvSp5LVZ97WInY/edit#gid=444251642)) e um botão abaixo do Iframe do maps "Abrir no google maps" 

Vai ser necessário solicitar a equipe de conteúdo para revisar a planilha e onde existir uma linha referente ao mapa adicionar a mesma localização. Quando a Url não existir o botão não vai aparecer

![image](https://user-images.githubusercontent.com/29258164/173716468-e1462d1b-3b52-4dee-8a87-1d16eeb2b487.png)

![image](https://user-images.githubusercontent.com/29258164/173716528-1c83a914-8713-41ab-bfe5-ba3fddb5a303.png)

![image](https://user-images.githubusercontent.com/29258164/173716774-09c5a25d-80a6-4f21-b916-84148bd97d75.png)

2022-06-15 10:28 UTC, alissonpeloso requested changes
Acho que o botão ficaria melhor com a cor principal de preenchimento e o texto em branco ou preto (aquele que der mais contraste). O botão com a mesma cor do fundo não destaca muito

2022-06-27 00:33 UTC, CleissonVieira commented
Botão ajustado, não tinha visto o comentário...

![image](https://user-images.githubusercontent.com/29258164/175840274-d06163fb-a17b-4b22-9066-0e23d7a870f8.png)

2022-06-27 11:17 UTC, alissonpeloso commented
@CleissonVieira, não sei se vc testou no aplicativo, mas o target _blank está fazendo criar uma aba de navegador além de abrir o maps. Acredito que seja melhor remover ele.

2022-06-27 11:20 UTC, alissonpeloso requested changes

2022-06-27 11:20 UTC, alissonpeloso commented on src/js/content.js
> +        )+`${data.extra ? '<button class="col button button-fill button-round"><a style="color:white;" class="link external" target="_blank" href="'+data.extra+'">Abrir no google maps</a></button>' :
```suggestion
        )+`${data.extra ? '<button class="col button button-fill button-round"><a style="color:white;" class="link external"  href="'+data.extra+'">Abrir no google maps</a></button>' : ''}`;
```

2022-06-29 03:05 UTC, CleissonVieira commented
> @CleissonVieira, não sei se vc testou no aplicativo, mas o target _blank está fazendo criar uma aba de navegador além de abrir o maps. Acredito que seja melhor remover ele.

Não cheguei a gerar build pra testar o apk, perfeito, obrigado pela info

2022-06-29 11:05 UTC, merged